### ISSUE TITLE
Mixin, that generates a docker image

### ISSUE THREAD

**Issue by svennela** [deislabs/porter-skeletor#10]
I see porter creates the docker image and runs the mixins inside the docker image. I am trying to create a mixin, that generates a docker image. Is it possible to create a mixin that generates the docker image?

**Comment by carolynvs** [comment]
@svennela It depends on what you are looking to do. Let me give you two options with different porter-specific terms:

1. mixin that can do docker builds. Essentially this mixin would embed the docker cli into the invocation image, and you can build docker images with it. It would _not_ replace the `porter build` step that builds the invocation image for bundles but would let you build regular docker images when your bundle is running. We have an open issue for that in the main Porter repository: https://github.com/deislabs/porter/issues/152
2. plugin that handles building the invocation image during `porter build`, for example to perform the build against a remote docker engine instead of the local one.

I am guessing that you mean #1, if you want to do that the best place to start is follwing the readme in this repository (porter-skeletor).

The trick will be perhaps adding a feature to porter to make sure that you have access to the same docker daemon, e.g. docker sock, env vars, etc, that porter used when it executed the bundle. I don't think we expose it now to the executing bundle but it's possible for porter to do so.

**Comment by svennela** [comment]
that's right, I am talking about option1. More specifically I am talking pack cli (https://github.com/buildpack/pack/releases), which does source to the image.

Thank you for your response. 
Sridhar

**Comment by carolynvs** [comment]
@svennela I've created an issue in the main porter repo [Request: Pack mixin](https://github.com/deislabs/porter/issues/816) to track the request for a new mixin and explain how to make it. If you don't mind, I'm going to close this one just so that there's no confusion for people about which one is the main issue and how to address it.

Thanks for the suggestion and let me know if you'd like try creating the mixin yourself!
